//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyffUAutoFSPro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlyffUAutoFSPro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hotkey.
        /// </summary>
        public static string addcustomhotkey {
            get {
                return ResourceManager.GetString("addcustomhotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Ress.
        /// </summary>
        public static string autoress {
            get {
                return ResourceManager.GetString("autoress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the main player dies, Resurrection is automatically executed..
        /// </summary>
        public static string autoress_tooltip {
            get {
                return ResourceManager.GetString("autoress_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BarSwitcher {
            get {
                object obj = ResourceManager.GetObject("BarSwitcher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BarSwitcherGray {
            get {
                object obj = ResourceManager.GetObject("BarSwitcherGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        public static string bot {
            get {
                return ResourceManager.GetString("bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs.
        /// </summary>
        public static string buffs {
            get {
                return ResourceManager.GetString("buffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy License.
        /// </summary>
        public static string buylicense {
            get {
                return ResourceManager.GetString("buylicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        public static string captcha {
            get {
                return ResourceManager.GetString("captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream captcha_detected_s1 {
            get {
                return ResourceManager.GetStream("captcha_detected_s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream captcha_detected_s2 {
            get {
                return ResourceManager.GetStream("captcha_detected_s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Captcha1 {
            get {
                object obj = ResourceManager.GetObject("Captcha1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Captcha2 {
            get {
                object obj = ResourceManager.GetObject("Captcha2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha Detection.
        /// </summary>
        public static string captchadetection {
            get {
                return ResourceManager.GetString("captchadetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a captcha appears in the screen, the bot plays a short sound..
        /// </summary>
        public static string captchadetection_tooltip {
            get {
                return ResourceManager.GetString("captchadetection_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string captchadetectionsound {
            get {
                return ResourceManager.GetString("captchadetectionsound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound is played when a captcha is recognized on the screen..
        /// </summary>
        public static string captchadetectionsound_tooltip {
            get {
                return ResourceManager.GetString("captchadetectionsound_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check distance.
        /// </summary>
        public static string checkdistance {
            get {
                return ResourceManager.GetString("checkdistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot checks the distance to the player and heals/buffs him only when he is near. Attention! We recommend to use this function only with 1v1 players because with AOE players important elements for the analysis are hidden by the monsters..
        /// </summary>
        public static string checkdistance_tooltip {
            get {
                return ResourceManager.GetString("checkdistance_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check License.
        /// </summary>
        public static string checklicense {
            get {
                return ResourceManager.GetString("checklicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Update.
        /// </summary>
        public static string checkupdate {
            get {
                return ResourceManager.GetString("checkupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear target.
        /// </summary>
        public static string cleartarget {
            get {
                return ResourceManager.GetString("cleartarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to deselect the target. By default it is the ESC key..
        /// </summary>
        public static string cleartarget_tooltip {
            get {
                return ResourceManager.GetString("cleartarget_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to reset hotkey.
        /// </summary>
        public static string clicktoresethotkey {
            get {
                return ResourceManager.GetString("clicktoresethotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set hotkey.
        /// </summary>
        public static string clicktosethotkey {
            get {
                return ResourceManager.GetString("clicktosethotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Healing.
        /// </summary>
        public static string criticalhealing {
            get {
                return ResourceManager.GetString("criticalhealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical healing value cannot be greater than the normal healing value..
        /// </summary>
        public static string criticalhealing_not_bigger_than_normal {
            get {
                return ResourceManager.GetString("criticalhealing_not_bigger_than_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the HP of the selected player falls below the specified value, a critical heal is performed. Healing is performed for several seconds without pause..
        /// </summary>
        public static string criticalhealing_tooltip {
            get {
                return ResourceManager.GetString("criticalhealing_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical healing duration.
        /// </summary>
        public static string criticalhealingduration {
            get {
                return ResourceManager.GetString("criticalhealingduration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies how long a critical heal should be performed. Player will be healed for X seconds without pause..
        /// </summary>
        public static string criticalhealingduration_tooltip {
            get {
                return ResourceManager.GetString("criticalhealingduration_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the Global Hotkey {0}?.
        /// </summary>
        public static string deleteglobalhotkey {
            get {
                return ResourceManager.GetString("deleteglobalhotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Hotkey-Action wirklich löschen?.
        /// </summary>
        public static string deleteglobalhotkeyitem {
            get {
                return ResourceManager.GetString("deleteglobalhotkeyitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test period finished.
        /// </summary>
        public static string demoend {
            get {
                return ResourceManager.GetString("demoend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeselectIconPlayer {
            get {
                object obj = ResourceManager.GetObject("DeselectIconPlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom detect.
        /// </summary>
        public static string detectzoom {
            get {
                return ResourceManager.GetString("detectzoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your Windows zoom in the display settings. The bot will only work with a scaling and arrangement of 100%..
        /// </summary>
        public static string detectzoom_description {
            get {
                return ResourceManager.GetString("detectzoom_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not activ.
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string donate {
            get {
                return ResourceManager.GetString("donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time between buffs.
        /// </summary>
        public static string durationbetweenbuffs {
            get {
                return ResourceManager.GetString("durationbetweenbuffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on the magic acceleration, this time can be set shorter. If the time is set too short, it is possible that buffs are not executed when rebuffing. Setting does not affect the buff Heal or Heal Rain.
        /// </summary>
        public static string durationbetweenbuffs_tooltip {
            get {
                return ResourceManager.GetString("durationbetweenbuffs_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter-Button to deactivate hotkey.
        /// </summary>
        public static string enterforreset {
            get {
                return ResourceManager.GetString("enterforreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter License.
        /// </summary>
        public static string enterlicense {
            get {
                return ResourceManager.GetString("enterlicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter license.
        /// </summary>
        public static string enterlicense_tooltip {
            get {
                return ResourceManager.GetString("enterlicense_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string erroroccurred {
            get {
                return ResourceManager.GetString("erroroccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey {0} is executed.
        /// </summary>
        public static string executehotkey {
            get {
                return ResourceManager.GetString("executehotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string follow {
            get {
                return ResourceManager.GetString("follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow traget (Z).
        /// </summary>
        public static string followZ {
            get {
                return ResourceManager.GetString("followZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to follow a target. By default it is the letter Z..
        /// </summary>
        public static string followZ_tooltip {
            get {
                return ResourceManager.GetString("followZ_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP Potion:.
        /// </summary>
        public static string fppotion {
            get {
                return ResourceManager.GetString("fppotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey for potions and other items to restore FP..
        /// </summary>
        public static string fppotion_tooltip {
            get {
                return ResourceManager.GetString("fppotion_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FPText {
            get {
                object obj = ResourceManager.GetObject("FPText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Hotkeys.
        /// </summary>
        public static string globalhotkeys {
            get {
                return ResourceManager.GetString("globalhotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GoodHPPixelColors {
            get {
                object obj = ResourceManager.GetObject("GoodHPPixelColors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GT Autorebuff.
        /// </summary>
        public static string gtautorebuff {
            get {
                return ResourceManager.GetString("gtautorebuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this setting, the Geburah Tiphreth (GT) buff is automatically re-buffed after the specified time..
        /// </summary>
        public static string gtautorebuff_tooltipp {
            get {
                return ResourceManager.GetString("gtautorebuff_tooltipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GT is automatically rebuffed after the specified seconds. .
        /// </summary>
        public static string gtautorebuff_value_tooltip {
            get {
                return ResourceManager.GetString("gtautorebuff_value_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        public static string heal {
            get {
                return ResourceManager.GetString("heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal / Heal Rain.
        /// </summary>
        public static string heal_healrain {
            get {
                return ResourceManager.GetString("heal_healrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection between which skill the heal bot should use. Note: Skill must be available in the skill tree and have at least level 1..
        /// </summary>
        public static string heal_healrain_tooltip {
            get {
                return ResourceManager.GetString("heal_healrain_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing.
        /// </summary>
        public static string healing {
            get {
                return ResourceManager.GetString("healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal Rain.
        /// </summary>
        public static string healrain {
            get {
                return ResourceManager.GetString("healrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey is already in use and cannot be used again..
        /// </summary>
        public static string hotkeyalreadyinuse {
            get {
                return ResourceManager.GetString("hotkeyalreadyinuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string hotkeys {
            get {
                return ResourceManager.GetString("hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP Potion:.
        /// </summary>
        public static string hppotion {
            get {
                return ResourceManager.GetString("hppotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey for food and other items to restore HP..
        /// </summary>
        public static string hppotion_tooltip {
            get {
                return ResourceManager.GetString("hppotion_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HPText {
            get {
                object obj = ResourceManager.GetObject("HPText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN DISCORD.
        /// </summary>
        public static string joindiscord {
            get {
                return ResourceManager.GetString("joindiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License already in use.
        /// </summary>
        public static string license_in_use {
            get {
                return ResourceManager.GetString("license_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXXXXXXX-XXXXXXXX-XXXXXXXX-XXXXXXXX.
        /// </summary>
        public static string licenseexample {
            get {
                return ResourceManager.GetString("licenseexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License released.
        /// </summary>
        public static string licensereleased {
            get {
                return ResourceManager.GetString("licensereleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License successfully registered.
        /// </summary>
        public static string licensregistersuccess {
            get {
                return ResourceManager.GetString("licensregistersuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not on screen.
        /// </summary>
        public static string maindistancenotonscreen {
            get {
                return ResourceManager.GetString("maindistancenotonscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In calibration.
        /// </summary>
        public static string maindistanceoncalibration {
            get {
                return ResourceManager.GetString("maindistanceoncalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To far away.
        /// </summary>
        public static string maindistancetofaraway {
            get {
                return ResourceManager.GetString("maindistancetofaraway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Hotkeys.
        /// </summary>
        public static string mirror {
            get {
                return ResourceManager.GetString("mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the global hotkeys you can execute action sequences by a key combination in the bot without the bot window having to be actively open. For example, you can press a key combination on your main so that the FS buffs Holy Guard before an AOE. Just test it out. Set any key combination to the Global Hotkey Rebuff, start the bot, select your main, minimize the bot and press the key combination on your main. You will see that the FS rebuffs you by magic. For example, you can also make the bot rise to a flying [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mirror_tooltip {
            get {
                return ResourceManager.GetString("mirror_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_ache {
            get {
                object obj = ResourceManager.GetObject("motion_ache", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_ache_search {
            get {
                object obj = ResourceManager.GetObject("motion_ache_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_ache_search1 {
            get {
                object obj = ResourceManager.GetObject("motion_ache_search1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_aha {
            get {
                object obj = ResourceManager.GetObject("motion_aha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_aha_search {
            get {
                object obj = ResourceManager.GetObject("motion_aha_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_anger {
            get {
                object obj = ResourceManager.GetObject("motion_anger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_anger_search {
            get {
                object obj = ResourceManager.GetObject("motion_anger_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_blush {
            get {
                object obj = ResourceManager.GetObject("motion_blush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_blush_search {
            get {
                object obj = ResourceManager.GetObject("motion_blush_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_catface {
            get {
                object obj = ResourceManager.GetObject("motion_catface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_catface_search {
            get {
                object obj = ResourceManager.GetObject("motion_catface_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_confused {
            get {
                object obj = ResourceManager.GetObject("motion_confused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_confused_search {
            get {
                object obj = ResourceManager.GetObject("motion_confused_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_crazy {
            get {
                object obj = ResourceManager.GetObject("motion_crazy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_crazy_search {
            get {
                object obj = ResourceManager.GetObject("motion_crazy_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_embarrassed {
            get {
                object obj = ResourceManager.GetObject("motion_embarrassed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_embarrassed_search {
            get {
                object obj = ResourceManager.GetObject("motion_embarrassed_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_glare {
            get {
                object obj = ResourceManager.GetObject("motion_glare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_glare_search {
            get {
                object obj = ResourceManager.GetObject("motion_glare_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_help {
            get {
                object obj = ResourceManager.GetObject("motion_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_help_search {
            get {
                object obj = ResourceManager.GetObject("motion_help_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_hunger {
            get {
                object obj = ResourceManager.GetObject("motion_hunger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_hunger_search {
            get {
                object obj = ResourceManager.GetObject("motion_hunger_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_kiss {
            get {
                object obj = ResourceManager.GetObject("motion_kiss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_kiss_search {
            get {
                object obj = ResourceManager.GetObject("motion_kiss_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_laugh {
            get {
                object obj = ResourceManager.GetObject("motion_laugh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_laugh_search {
            get {
                object obj = ResourceManager.GetObject("motion_laugh_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_love {
            get {
                object obj = ResourceManager.GetObject("motion_love", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_love_search {
            get {
                object obj = ResourceManager.GetObject("motion_love_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_mad {
            get {
                object obj = ResourceManager.GetObject("motion_mad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_mad_search {
            get {
                object obj = ResourceManager.GetObject("motion_mad_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_oh {
            get {
                object obj = ResourceManager.GetObject("motion_oh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_oh_search {
            get {
                object obj = ResourceManager.GetObject("motion_oh_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_ouch {
            get {
                object obj = ResourceManager.GetObject("motion_ouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_ouch_search {
            get {
                object obj = ResourceManager.GetObject("motion_ouch_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_rich {
            get {
                object obj = ResourceManager.GetObject("motion_rich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_rich_search {
            get {
                object obj = ResourceManager.GetObject("motion_rich_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_ridicule {
            get {
                object obj = ResourceManager.GetObject("motion_ridicule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_ridicule_search {
            get {
                object obj = ResourceManager.GetObject("motion_ridicule_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sad {
            get {
                object obj = ResourceManager.GetObject("motion_sad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sad_search {
            get {
                object obj = ResourceManager.GetObject("motion_sad_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sigh {
            get {
                object obj = ResourceManager.GetObject("motion_sigh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sigh_search {
            get {
                object obj = ResourceManager.GetObject("motion_sigh_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sleepy {
            get {
                object obj = ResourceManager.GetObject("motion_sleepy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sleepy_search {
            get {
                object obj = ResourceManager.GetObject("motion_sleepy_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sneer {
            get {
                object obj = ResourceManager.GetObject("motion_sneer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sneer_search {
            get {
                object obj = ResourceManager.GetObject("motion_sneer_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sparkle {
            get {
                object obj = ResourceManager.GetObject("motion_sparkle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sparkle_search {
            get {
                object obj = ResourceManager.GetObject("motion_sparkle_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_surprise {
            get {
                object obj = ResourceManager.GetObject("motion_surprise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_surprise_search {
            get {
                object obj = ResourceManager.GetObject("motion_surprise_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sweat {
            get {
                object obj = ResourceManager.GetObject("motion_sweat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_sweat_search {
            get {
                object obj = ResourceManager.GetObject("motion_sweat_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_tongue {
            get {
                object obj = ResourceManager.GetObject("motion_tongue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_tongue_search {
            get {
                object obj = ResourceManager.GetObject("motion_tongue_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_wink {
            get {
                object obj = ResourceManager.GetObject("motion_wink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_wink_search {
            get {
                object obj = ResourceManager.GetObject("motion_wink_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_yummy {
            get {
                object obj = ResourceManager.GetObject("motion_yummy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motion_yummy_search {
            get {
                object obj = ResourceManager.GetObject("motion_yummy_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect emoji.
        /// </summary>
        public static string motionrebuff {
            get {
                return ResourceManager.GetString("motionrebuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this setting a rebuff can be started by an emoji sent by the selected player. This means that the bot does not have to be called for a rebuff and can run completely in the background..
        /// </summary>
        public static string motionrebuff_tooltip {
            get {
                return ResourceManager.GetString("motionrebuff_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP Potion:.
        /// </summary>
        public static string mppotion {
            get {
                return ResourceManager.GetString("mppotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey for potions and other items to restore MP..
        /// </summary>
        public static string mppotion_tooltip {
            get {
                return ResourceManager.GetString("mppotion_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MPText {
            get {
                object obj = ResourceManager.GetObject("MPText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign Geburah Tiphret in the skill tab first before this function can be activated..
        /// </summary>
        public static string mustsetgtbefore {
            get {
                return ResourceManager.GetString("mustsetgtbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign Heal-Action in the skill tab first before this function can be activated..
        /// </summary>
        public static string mustsethealingbefore {
            get {
                return ResourceManager.GetString("mustsethealingbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign Holy Guard  in the skill tab first before this function can be activated..
        /// </summary>
        public static string mustsetholyguardbefore {
            get {
                return ResourceManager.GetString("mustsetholyguardbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign Resurrection-Action in the skill tab first before this function can be activated..
        /// </summary>
        public static string mustsetresurrectionbefore {
            get {
                return ResourceManager.GetString("mustsetresurrectionbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Status.
        /// </summary>
        public static string mystatus {
            get {
                return ResourceManager.GetString("mystatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Healing.
        /// </summary>
        public static string normalhealing {
            get {
                return ResourceManager.GetString("normalhealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal healing value cannot be smaller than critical healing value..
        /// </summary>
        public static string normalhealing_not_smaller_than_critical {
            get {
                return ResourceManager.GetString("normalhealing_not_smaller_than_critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the HP of the selected player falls below the specified value, a one-time healing is performed..
        /// </summary>
        public static string normalhealing_tooltip {
            get {
                return ResourceManager.GetString("normalhealing_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available.
        /// </summary>
        public static string noupdateavailable {
            get {
                return ResourceManager.GetString("noupdateavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Bot.
        /// </summary>
        public static string pausebot {
            get {
                return ResourceManager.GetString("pausebot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this setting the bot can be paused for a short time when keys or mouse clicks are executed in the browser. Good to be able to quickly intervene in certain events, e.g. attacks from aggro mobs..
        /// </summary>
        public static string pausebot_tooltip {
            get {
                return ResourceManager.GetString("pausebot_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string pausebottime {
            get {
                return ResourceManager.GetString("pausebottime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot wird für X Sekunden bei Interaktionen mit Tastatur oder Maus pausiert..
        /// </summary>
        public static string pausebottime_tooltip {
            get {
                return ResourceManager.GetString("pausebottime_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PlayerSelectX {
            get {
                object obj = ResourceManager.GetObject("PlayerSelectX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waits for keystroke ....
        /// </summary>
        public static string presskey {
            get {
                return ResourceManager.GetString("presskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key or key combination.
        /// </summary>
        public static string presskeydescription {
            get {
                return ResourceManager.GetString("presskeydescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuff.
        /// </summary>
        public static string rebuff {
            get {
                return ResourceManager.GetString("rebuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuff after Resurrection.
        /// </summary>
        public static string rebuffafterresurrection {
            get {
                return ResourceManager.GetString("rebuffafterresurrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start rebuff after Resurrection.
        /// </summary>
        public static string rebuffafterresurrection_tooltip {
            get {
                return ResourceManager.GetString("rebuffafterresurrection_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuff GT.
        /// </summary>
        public static string rebuffgt {
            get {
                return ResourceManager.GetString("rebuffgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow automatically.
        /// </summary>
        public static string refollow {
            get {
                return ResourceManager.GetString("refollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command to follow the target is executed in the defined time interval. Default key Z. Key can be changed under Hotkeys..
        /// </summary>
        public static string refollow_tooltip {
            get {
                return ResourceManager.GetString("refollow_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow interval.
        /// </summary>
        public static string refollowinterval {
            get {
                return ResourceManager.GetString("refollowinterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time interval in which the key is pressed again for follow..
        /// </summary>
        public static string refollowinterval_tooltip {
            get {
                return ResourceManager.GetString("refollowinterval_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release license.
        /// </summary>
        public static string releaselicense {
            get {
                return ResourceManager.GetString("releaselicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License can be activated only on one computer at a time. Upon release, your license will be released and you can use it again on another computer. .
        /// </summary>
        public static string releaselicense_tooltip {
            get {
                return ResourceManager.GetString("releaselicense_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings. Your Linzens will not be lost..
        /// </summary>
        public static string reset_tooltip {
            get {
                return ResourceManager.GetString("reset_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resurrects .
        /// </summary>
        public static string resurrects {
            get {
                return ResourceManager.GetString("resurrects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot {
            get {
                object obj = ResourceManager.GetObject("Screenshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow1BottomLeft {
            get {
                object obj = ResourceManager.GetObject("SelectArrow1BottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow1BottomRight {
            get {
                object obj = ResourceManager.GetObject("SelectArrow1BottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow1TopLeft {
            get {
                object obj = ResourceManager.GetObject("SelectArrow1TopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow1TopRight {
            get {
                object obj = ResourceManager.GetObject("SelectArrow1TopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow2BottomLeft {
            get {
                object obj = ResourceManager.GetObject("SelectArrow2BottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow2BottomRight {
            get {
                object obj = ResourceManager.GetObject("SelectArrow2BottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow2TopLeft {
            get {
                object obj = ResourceManager.GetObject("SelectArrow2TopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow2TopRight {
            get {
                object obj = ResourceManager.GetObject("SelectArrow2TopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow3BottomLeft {
            get {
                object obj = ResourceManager.GetObject("SelectArrow3BottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow3BottomRight {
            get {
                object obj = ResourceManager.GetObject("SelectArrow3BottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow3TopLeft {
            get {
                object obj = ResourceManager.GetObject("SelectArrow3TopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow3TopRight {
            get {
                object obj = ResourceManager.GetObject("SelectArrow3TopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow4BottomLeft {
            get {
                object obj = ResourceManager.GetObject("SelectArrow4BottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow4BottomRight {
            get {
                object obj = ResourceManager.GetObject("SelectArrow4BottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow4TopLeft {
            get {
                object obj = ResourceManager.GetObject("SelectArrow4TopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow4TopRight {
            get {
                object obj = ResourceManager.GetObject("SelectArrow4TopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow5BottomLeft {
            get {
                object obj = ResourceManager.GetObject("SelectArrow5BottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow5BottomRight {
            get {
                object obj = ResourceManager.GetObject("SelectArrow5BottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow5TopLeft {
            get {
                object obj = ResourceManager.GetObject("SelectArrow5TopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SelectArrow5TopRight {
            get {
                object obj = ResourceManager.GetObject("SelectArrow5TopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Player.
        /// </summary>
        public static string selectedplayer {
            get {
                return ResourceManager.GetString("selectedplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Heal.
        /// </summary>
        public static string selfhealprotection {
            get {
                return ResourceManager.GetString("selfhealprotection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the own HP falls below the defined value then the selected player is deselected (ESC) and the self-healing is started. Useful when even faster healing is needed to survive attacks from aggro monsters. If Heal Rain is used, the player is not deselected..
        /// </summary>
        public static string selfhealprotection_tooltipp {
            get {
                return ResourceManager.GetString("selfhealprotection_tooltipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-healing value must be less than {0}%..
        /// </summary>
        public static string selfhealprotection_value_smaller_then_hppotion_value {
            get {
                return ResourceManager.GetString("selfhealprotection_value_smaller_then_hppotion_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the own HP falls below this value, the self healing is activated. .
        /// </summary>
        public static string selfhealprotection_value_tooltip {
            get {
                return ResourceManager.GetString("selfhealprotection_value_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string skills {
            get {
                return ResourceManager.GetString("skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status (T).
        /// </summary>
        public static string statusT {
            get {
                return ResourceManager.GetString("statusT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to open the status window. By default it is the letter T..
        /// </summary>
        public static string statusT_tooltip {
            get {
                return ResourceManager.GetString("statusT_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred. Please request help on discord.
        /// </summary>
        public static string unknowerroroccurred {
            get {
                return ResourceManager.GetString("unknowerroroccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available. Go to Discord to download the latest version..
        /// </summary>
        public static string updateavailable {
            get {
                return ResourceManager.GetString("updateavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usefull.
        /// </summary>
        public static string usefull {
            get {
                return ResourceManager.GetString("usefull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use HP Potion on:.
        /// </summary>
        public static string usehppotion {
            get {
                return ResourceManager.GetString("usehppotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the HP falls below the defined value, an HP potion is used..
        /// </summary>
        public static string usehppotion_tooltip {
            get {
                return ResourceManager.GetString("usehppotion_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use MP Potion on:.
        /// </summary>
        public static string usemppotion {
            get {
                return ResourceManager.GetString("usemppotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the MP falls below the defined value, an MP potion is used..
        /// </summary>
        public static string usemppotion_tooltip {
            get {
                return ResourceManager.GetString("usemppotion_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid combination.
        /// </summary>
        public static string wrongkeycombination {
            get {
                return ResourceManager.GetString("wrongkeycombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please have at least {0} normal key/s and at least {1} system key/s ( Strg, Ctrl, Shift ) available..
        /// </summary>
        public static string wrongkeycombination_message {
            get {
                return ResourceManager.GetString("wrongkeycombination_message", resourceCulture);
            }
        }
    }
}
